name: Go CI CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: checkout code
        uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build aplikasi
      - name: Build
        run: go build -v ./...

      # Jalankan unit tests
      - name: Test
        run: go test -v ./...

      # Static analysis (opsional)
      - name: Run lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      #  docker hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ahmdrifai/golang-simple-cicd:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy ke vps
      - name: Deploy ke vps
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/golang-simple-cicd
            docker compose pull
            docker compose up -d
